/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as KetentuanRouteImport } from './routes/ketentuan'
import { Route as IndexRouteImport } from './routes/index'

const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const KetentuanRoute = KetentuanRouteImport.update({
  id: '/ketentuan',
  path: '/ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ketentuan': typeof KetentuanRoute
  '/sukses': typeof SuksesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ketentuan': typeof KetentuanRoute
  '/sukses': typeof SuksesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ketentuan': typeof KetentuanRoute
  '/sukses': typeof SuksesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ketentuan' | '/sukses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ketentuan' | '/sukses'
  id: '__root__' | '/' | '/ketentuan' | '/sukses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KetentuanRoute: typeof KetentuanRoute
  SuksesRoute: typeof SuksesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketentuan': {
      id: '/ketentuan'
      path: '/ketentuan'
      fullPath: '/ketentuan'
      preLoaderRoute: typeof KetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KetentuanRoute: KetentuanRoute,
  SuksesRoute: SuksesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
